Refactor gap css styles
DARPA-ASKEM/terarium pull request #3892
Opened 2024-06-17 15:11 UTC by asylves1

# Description

Added default values that match tailwind gaps to `_variables.scss`.
replaced some of the values for `.25rem`, `.5rem` & `.75rem`

Resolves #(issue)

2024-06-17 17:01 UTC, shawnyama approved these changes

2024-06-17 19:26 UTC, YohannParis reviewed
Just need to fix the extra space in front of all `var(--gap-1)`

2024-06-17 19:26 UTC, YohannParis commented on packages/client/hmi-client/src/assets/css/theme/_variables.scss
> +	--gap-88: 22rem;
```suggestion
```
Those are not necessary.

2024-06-17 19:26 UTC, YohannParis commented on packages/client/hmi-client/src/assets/css/theme/_variables.scss
> +	--gap-3-5: 0.875rem;			// 14px
does `.5` not work compared top `-5`?

2024-06-17 19:26 UTC, YohannParis commented on packages/client/hmi-client/src/assets/css/theme/designer/components/input/_autocomplete.scss
> +    padding-bottom:  var(--gap-1);
```suggestion
    padding-bottom: var(--gap-1);
```

2024-06-17 19:26 UTC, YohannParis commented on packages/client/hmi-client/src/assets/css/theme/extensions/_autocomplete.scss
> +            padding:  var(--gap-1) 1rem;
```suggestion
            padding: var(--gap-1) 1rem;
```

2024-06-20 20:18 UTC, asylves1 commented on packages/client/hmi-client/src/assets/css/theme/_variables.scss
> +	--gap-3-5: 0.875rem;			// 14px
Not for the variable name :(

2024-06-21 13:51 UTC, YohannParis requested changes
You still need to check **ALL** the `var(--gap-1)` because they **ALL** have a space in front of them.

2024-06-21 18:39 UTC, YohannParis approved these changes

2024-06-21 18:39 UTC, merged