Optimize success and intervention charts
DARPA-ASKEM/terarium pull request #4107
Opened 2024-07-11 19:57 UTC by blanchco

# Description

* Constraint Bar charts
* Interventions line charts (before lines only)

2024-07-11 20:12 UTC, blanchco commented on packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/tera-optimize-ciemss.vue
> +const preProcessedInterventionsData = computed<
I want to group and format the data for the interventions chart here...interventions such as beta can be created in separate cards, so I want to group them all together to be used in 1 chart

2024-07-11 20:23 UTC, mwdchang requested changes
We are likely going to tweak these charts several times, and they likely need to adapt to different circumstances, for example you can imagine the charts need be rendered as:
- small preview with no interactions
- fullsize in the operator drilldown with interactions
- fullsize but not interactive in the report, whatever that may be

So I am thinking we might as well bite the bullet now, and have these spec generations in vanilla javascript/typescript rather than as computed properties of the Vue-framework.  
This would make it easier to customize things and make this feature more portable; plus, your template-sections are effectively pass-throughs calling "vega-chart".


I would imagine something like this

```
<vega-chart  :visualization-spec="interventionChartSpec" />
...
<vega-chart  :visualization-spec="optimizeChartSpec" />

```

Where

```
const interventionChartSpec = createInterventionChart(data, blah blah config, .....)
const optimizeChartSpec = createOptimizeChart(data, blah blah config, .....)
```

2024-07-12 01:02 UTC, blanchco commented
> We are likely going to tweak these charts several times, and they likely need to adapt to different circumstances, for example you can imagine the charts need be rendered as:
> 
> * small preview with no interactions
> * fullsize in the operator drilldown with interactions
> * fullsize but not interactive in the report, whatever that may be
> 
> So I am thinking we might as well bite the bullet now, and have these spec generations in vanilla javascript/typescript rather than as computed properties of the Vue-framework. This would make it easier to customize things and make this feature more portable; plus, your template-sections are effectively pass-throughs calling "vega-chart" and they don't add any additional elements per se.
> 
> I would imagine something like this
> 
> ```
> <vega-chart  :visualization-spec="interventionChartSpec" />
> ...
> <vega-chart  :visualization-spec="optimizeChartSpec" />
> ```
> 
> Where
> 
> ```
> const interventionChartSpec = createInterventionChart(data, blah blah config, .....)
> const optimizeChartSpec = createOptimizeChart(data, blah blah config, .....)
> ```

@mwdchang I've moved the logic and spec creation into the `optimize.ts` file and removed the chart components, is this more of what you were thinking of?

2024-07-12 12:39 UTC, YohannParis approved these changes

2024-07-12 13:20 UTC, mwdchang approved these changes

2024-07-12 13:24 UTC, merged