task: xDD wrapper for the external API (#384)
DARPA-ASKEM/TERArium pull request #414
Opened 2022-12-21 19:13 UTC by dvince2

Adding the documents and extraction service proxy api, as well as the needed configurations to build and run the service

# Description

Adding a new service layer to proxy the xdd document and extraction service.  This PR also requires changes to be made to the orchestration project before it can be committed

Resolves #384

2022-12-21 21:57 UTC, YohannParis approved these changes
LGTM

2022-12-21 21:57 UTC, YohannParis commented on packages/services/document-server/build.gradle
> +	//implementation "io.quarkus:quarkus-keycloak-authorization"
Why not removing it if not in use?

2022-12-21 21:57 UTC, YohannParis commented on packages/services/document-server/build.gradle
> +compileJava {
Missing a space between those two sets of definition.

2022-12-21 21:57 UTC, YohannParis commented on packages/services/document-server/docker/Dockerfile.jvm
> +###
Can we remove those comments? Or do they have any purpose other than being a Quarkus default?
@dgauldie?

2022-12-21 21:57 UTC, YohannParis commented on packages/services/document-server/docker/Dockerfile.jvm
> +EXPOSE 3030
Could we add those port to the main README.md of the repo?
Maybe a list of all Quarkus services and their ports, so we don't have to dig deep to find them.

2022-12-21 21:57 UTC, YohannParis commented on packages/services/document-server/docker/Dockerfile.native
> +###
Again this is all handle by the bake file, we don't really need them here.

2022-12-21 21:57 UTC, YohannParis commented on packages/services/document-server/src/main/java/software/uncharted/terarium/documentserver/proxies/xdd/DocumentProxy.java
> +@RegisterRestClient(configKey = "xdd-document-service")
Is this where you make reference to the xDD API URL in the `resources/application.properties`?
Then _Microprofile_ automaticaly does the REST call with the `@GET` annotation?

2023-01-03 14:58 UTC, dvince2 commented on packages/services/document-server/build.gradle
> +	//implementation "io.quarkus:quarkus-keycloak-authorization"
Good point! Thanks

2023-01-04 01:15 UTC, YohannParis approved these changes

2023-01-04 15:35 UTC, chris-dickson requested changes

2023-01-04 17:57 UTC, dvince2 commented on packages/services/document-server/src/main/java/software/uncharted/terarium/documentserver/models/xdd/XDDResponseOK.java
> +	private Number v;
These were copied from the original document code from HMI-Server.  Following up with what this is now to add documentation on it

2023-01-05 14:08 UTC, dvince2 commented on packages/services/document-server/src/main/java/software/uncharted/terarium/documentserver/models/xdd/XDDResponseOK.java
> +	private Number v;
Confirmed version

2023-01-09 15:59 UTC, chris-dickson submitted a review, later dismissed

2023-01-09 16:28 UTC, chris-dickson approved these changes

2023-01-09 18:29 UTC, merged