fix update project model name
DARPA-ASKEM/terarium pull request #4373
Opened 2024-08-06 21:31 UTC by blanchco

# Description

* Fix to update the project model name after editing

2024-08-07 16:45 UTC, YohannParis commented on packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectAssetService.java
> +				}
@dvince2 could we overwrite the `setName` of `Model.java` to write `Model.ModelHeader.name` at the same time as `Model.name`?

2024-08-07 16:53 UTC, mwdchang commented on packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectAssetService.java
> +				}
I almost feel like we should manage the editable parts (name, description) separately, and not within the asset (model, dataset ... etc).

2024-08-07 17:33 UTC, YohannParis commented on packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectAssetService.java
> +				}
I do not follow your resoning?

2024-08-07 18:28 UTC, mwdchang approved these changes

2024-08-12 13:25 UTC, dvince2 requested changes

2024-08-12 13:25 UTC, dvince2 commented on packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectAssetService.java
> +				}
Models already have a lot of custom logic happening inside of `ModelService.java`. If we need to have a custom `updateByAsset` for models it should be done in `ModelService` and override the other method (for example see `ModelService#updateAsset`.

As an aside, why is `projectAssetRepository.findByAssetId` returning a list? We're asking for an asset by ID... there should only be one asset returned ever.

2024-08-19 19:03 UTC, blanchco commented on packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/data/ProjectAssetService.java
> +				}
@dvince2 Setting the name now done on `ModelService.java` as suggested!

2024-08-19 19:25 UTC, dvince2 approved these changes

2024-08-19 19:34 UTC, merged