feat: funman graph interactions
DARPA-ASKEM/terarium pull request #5163
Opened 2024-10-16 16:40 UTC by shawnyama

# Description

* Include a summary of the changes and the related issue. 
* Include relevant motivation and context.

Resolves #(issue)

2024-10-17 20:08 UTC, YohannParis approved these changes

2024-10-17 20:42 UTC, mwdchang commented on packages/client/hmi-client/src/components/workflow/ops/funman/tera-funman-output.vue
> +				@chart-click="onParameterChartClick"
Can you explain a bit how the visual encodings work with respect to click on the parameters' rug plot? I played around with it and it is confusing what had been selected.

2024-10-17 20:45 UTC, mwdchang requested changes
Probably not directly related to this PR, but since you are working in the area: There is something strange with how you are collecting the trajectories for funman results. Notice below you have several markers on the same x-axis - this means it is no longer a function of time and is therefore incorrect.

<img width="760" alt="image" src="https://github.com/user-attachments/assets/895b2180-fdcd-4a55-815e-c6f433dd478a">

See: https://app.staging.terarium.ai/projects/33f364c1-1da2-4cf7-a176-9870ef1a3ab6/workflow/25bde950-a3c3-41b1-bf32-bfee8add72ae?operator=648f4cb2-ff15-4c01-907a-4b1b4e241dbc

2024-10-18 17:59 UTC, shawnyama commented
Added white borders to the ticks since they could be hard to see in these cases 
![image](https://github.com/user-attachments/assets/78c5f496-0a4a-4779-b703-f1cc5009fe37)

2024-10-18 18:04 UTC, YohannParis commented on packages/client/hmi-client/src/services/charts.ts
> +	console.log(trajectories);
```suggestion
```

2024-10-18 19:44 UTC, mwdchang approved these changes
Thanks, as discussed we probably want to revisit the parameter chart, making it larger and a bit more obvious what are the interactions and their respective responses. This is a good start.

2024-10-18 19:53 UTC, merged