feat(hmi-server): Exception Handling
DARPA-ASKEM/TERArium pull request #560
Opened 2023-01-26 20:19 UTC by dvince2

A WIP checkin to demonstrate exception handling in a very basic way. This also includes some cleanup work and serialization fixes for projects, assets and our home resource

# Description

* Include a summary of the changes and the related issue. 
* Include relevant motivation and context.

Resolves #no_issue

2023-01-30 15:54 UTC, Tom-Szendrey approved these changes
Thank you for all of the cleanup along with the logging!

2023-01-30 16:00 UTC, chris-dickson requested changes
On hold until a filled in description for the PR is provided.

2023-01-30 16:48 UTC, tangopapatime approved these changes
Looks good.  As you mentioned, an additional discussion or two about error handling and codes is needed which should also be properly documented :P

2023-01-31 15:29 UTC, chris-dickson approved these changes

2023-01-31 15:31 UTC, merged