Jamie templates style tweaks
DARPA-ASKEM/terarium pull request #5931
Opened 2024-12-23 22:20 UTC by jamiewaese-uncharted

misc style tweaks for the templates dialog
![Monosnap Terarium 2024-12-23 17-18-38](https://github.com/user-attachments/assets/d8dc8bfc-e11a-4d6d-aaab-2eeeba09d050)
![Monosnap Terarium 2024-12-23 17-19-44](https://github.com/user-attachments/assets/632bb9a3-0475-4608-91f0-2ec2fab1d4c8)
stuff like that

2024-12-24 13:47 UTC, mloppie approved these changes

2025-01-02 14:39 UTC, blanchco approved these changes

2025-01-02 14:50 UTC, blanchco requested changes

2025-01-02 14:50 UTC, blanchco commented on packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
> +	if (!runResults.value || !selectedRunId.value) return 0;
Not sure why we are changing this back here

2025-01-02 14:50 UTC, blanchco commented on packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
> -const solverStepSize = ref<number>(props.node.state.solverStepSize);
Are we getting rid of the solver step size in simulate?  If so we should get rid of it in the html template as well

2025-01-02 14:55 UTC, Tom-Szendrey commented on packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
> -const solverStepSize = ref<number>(props.node.state.solverStepSize);
We should not get rid of `solverStepSize` in simulate it should be editable in a `tera-input-number` which can be disabled depending on the selected `solver method`

2025-01-03 15:29 UTC, blanchco commented on packages/client/hmi-client/src/components/workflow/ops/simulate-ciemss/tera-simulate-ciemss-drilldown.vue
> -const solverStepSize = ref<number>(props.node.state.solverStepSize);
I've restore the step size, and I think it should be good now

2025-01-03 15:33 UTC, blanchco approved these changes

2025-01-03 15:33 UTC, merged